swagger: "2.0"
info:
  version: "0.0.0"
  title: instalike
host: localhost:2001
basePath: /
parameters:
  thing:
    name: thing
    in: query
    description: Entity hash
    required: true
    type: string
    default: '0000'
schemes:
  - http
produces:
  - application/json
basePath: /api/v0
paths:
  /{thing}:
    x-swagger-router-controller: thing
    parameters:
      - name: thing
        in: path
        description: hash
        required: true
        type: string
    get:
      description: Return the global count
      operationId: getLikes
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Thing"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Like an entity and return the global count
      operationId: like
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Thing"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  ErrorResponse:
    required:
      - Error
    properties:
      Error:
        type: string
  Thing:
    type: object
    required:
      - hash
    properties:
      id:
        type: string
        description: Implementation UUID
      hash:
        type: string
        description: User-facing identifier (case sensitive)
      count:
        type: integer
        description: Global count
  LogMessage:
    required:
      - message
    properties:
      message:
        type: string
        description: The message to log
