#!/bin/sh
# Run this script as root

apt-get update
# apt-get install -y make g++ git curl vim libcairo2-dev libav-tools nfs-common portmap # build tools
# apt-get install -y build-essential openssl libssl-dev pkg-config # node build dependencies
apt-get install -y redis-server nodejs npm
ln -sf /usr/bin/nodejs /usr/bin/node
npm install pm2 -g

# Setup (assuming net.ipv4.ip_forward=1 already)
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080
iptables -A INPUT -p tcp -m tcp --sport 80 -j ACCEPT
iptables -A OUTPUT -p tcp -m tcp --dport 80 -j ACCEPT
